name: Build TotalSolutionsFrontend Testing Branch

env:
  CI: false

on:
  workflow_dispatch:
    inputs:
      reponame:
        description: 'Subroute of repo to build'
        required: false
        default: 'root'
        type: string

permissions:
  contents: write

jobs:
  build-repo:
    runs-on: ubuntu-latest
    environment: env_test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PATOKEN }}

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Fish
        run: |
          sudo apt-get update
          sudo apt-get install -y fish

      - name: Set Execute Permission
        run: chmod +x .github/build.fish

      - name: Build
        run: |
          cd .github && fish ./build.fish ${{ inputs.reponame }}
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}

      - name: Commit & Push
        run: |
          git config --global user.name "tad-org-bot"
          git config --global user.email "bot@users.noreply.github.com"

          cp -r .github/site/* .
          rm -rf .github/site

          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Portal Build (automated)"
          git push
